---
image: "buluma/github-action-molecule:5.1.1"

variables:
  PY_COLORS: 1

molecule:
  script:
    - molecule test
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
  allow_failure: true
  parallel:
    matrix:
      - image: "docker-ubuntu-systemd"
        tag: "focal"
      - image: "docker-ubuntu-systemd"
        tag: "bionic"
      - image: "debian-systemd"
        tag: "bullseye"

galaxy:
  script:
    - ansible-galaxy role import --api-key ${GALAXY_API_KEY} buluma ${CI_PROJECT_NAME}
  rules:
    - if: $CI_COMMIT_TAG != null
