---
- name: copy jemalloc rpm file to server
  ansible.builtin.copy:
     # src: http://download-ib01.fedoraproject.org/pub/epel/$releasever/$basearch/
     src: https://download-ib01.fedoraproject.org/pub/epel/7/x86_64/Packages/j/jemalloc-3.6.0-1.el7.x86_64.rpm
     dest: /tmp/jemalloc-3.6.0-1.el7.x86_64.rpm
     mode: 0644
     remote_src: yes

- name: Import Jemalloc EPEL GPG key.
  rpm_key:
     key: "{{ varnish_repo_gpg_key_url }}"
     state: present
  register: result
  until: result is succeeded
  retries: 5
  delay: 10
  # when: not epel_repofile_result.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"

- name: install jemalloc package.
  ansible.builtin.yum:
     name: /tmp/jemalloc-3.6.0-1.el7.x86_64.rpm
     state: present

- name: ensure varnish dependency is installed.
  ansible.builtin.yum:
     name:
        - yum-utils
        - jemalloc
     state: present

- name: ensure extra varnish dependency on older RHEL versions is installed.
  ansible.builtin.yum:
     name: pygpgme
     state: present
  when: ansible_distribution_major_version | int < 8

- name: add Varnish packagecloud.io yum repo.
  ansible.builtin.yum_repository:
     name: varnishcache_{{ varnish_packagecloud_repo }}
     description: Varnish Cache packagecloud.io repository.
     baseurl: "{{ varnish_yum_repo_baseurl }}"
     repo_gpgcheck: false
     gpgcheck: false
     enabled: true
     gpgkey: https://packagecloud.io/varnishcache/{{ varnish_packagecloud_repo }}/gpgkey
     sslverify: 1
     sslcacert: /etc/pki/tls/certs/ca-bundle.crt
     priority: "{{ varnish_packagecloud_repo_yum_repository_priority }}"
  register: varnish_packagecloud_repo_addition

- name: refresh yum metadata cache if repo changed.
  command: >
    yum -q makecache -y --disablerepo='*' --enablerepo='varnishcache_{{ varnish_packagecloud_repo }}'
  args:
     warn: false
  when: varnish_packagecloud_repo_addition.changed
  tags: ['skip_ansible_lint']

- name: disable varnish AppStream in RHEL 8.
  command: dnf module disable -y varnish
  args:
     warn: false
  when:
     - varnish_packagecloud_repo_addition.changed
     - ansible_distribution_major_version | int == 8
  tags: ['skip_ansible_lint']

- name: ensure Varnish is installed.
  ansible.builtin.yum:
     name: "{{ varnish_package_name }}"
     state: present
