---
- name: ensure dependencies are present.
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - gnupg2
      - jemalloc
    state: present

- name: add packagecloud.io Varnish apt key.
  ansible.builtin.apt_key:
    url: https://packagecloud.io/varnishcache/{{ varnish_packagecloud_repo }}/gpgkey
    state: present

- name: add packagecloud.io Varnish apt repository.
  ansible.builtin.apt_repository:
    repo: "{{ varnish_apt_repo }}"
    state: present

- name: ensure Varnish is installed.
  ansible.builtin.apt:
    name: "{{ varnish_package_name }}"
    state: present

- name: ensure old role-managed Varnish systemd unit file is removed.
  ansible.builtin.file:
    path: /etc/systemd/system/varnish.service
    state: absent
  when: varnish_systemd_config_path != '/etc/systemd/system'
