---
- name: setup-RedHat | Ensure Varnish dependency is installed.
  ansible.builtin.dnf:
    name: yum-utils
    state: present
- name: setup-RedHat | Ensure extra Varnish dependency on older RHEL versions is installed.
  ansible.builtin.dnf:
    name: pygpgme
    state: present
  when: ansible_distribution_major_version | int < 8
- name: setup-RedHat | Add Varnish packagecloud.io yum repo.
  ansible.builtin.yum_repository:
    baseurl: "{{ varnish_yum_repo_baseurl }}"
    description: Varnish Cache packagecloud.io repository.
    enabled: true
    gpgcheck: false
    gpgkey: https://packagecloud.io/varnishcache/{{ varnish_packagecloud_repo }}/gpgkey
    module_hotfixes: true
    name: varnishcache_{{ varnish_packagecloud_repo }}
    priority: "{{ varnish_packagecloud_repo_yum_repository_priority }}"
    repo_gpgcheck: false
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt
    sslverify: 1
  register: varnish_packagecloud_repo_addition
- ansible.builtin.command: "yum -q makecache -y --disablerepo='*' --enablerepo='varnishcache_{{ varnish_packagecloud_repo }}'\n"
  name: setup-RedHat | Refresh yum metadata cache if repo changed.
  tags:
    - skip_ansible_lint
  when: varnish_packagecloud_repo_addition.changed
- name: setup-RedHat | Ensure Varnish is installed.
  ansible.builtin.dnf:
    name: "{{ varnish_package_name }}"
    state: present
- name: setup-RedHat | Ensure Varnish VMODs are installed.
  ansible.builtin.dnf:
    name: "{{ varnish_modules_package_name }}"
    state: present
  when: varnish_modules_package_name
