---
- name: Reload systemd
  ansible.builtin.systemd: daemon_reload=true

- name: Restart varnish
  ansible.builtin.service: name=varnish state=restarted
  changed_when: no
  failed_when: no

- name: Restart service cron on centos
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: varnish
