---
- name: Reload systemd
  ansible.builtin.systemd: daemon_reload=true

- name: Restart varnish
  ansible.builtin.service: name=varnish state=restarted
  changed_when: false
  failed_when: false

- name: Restart service cron on centos
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: varnish
