---
- name: Converge
  hosts: all
  become: true
  vars:
    varnish_apt_use_packagecloud: false
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

  roles:
    - role: buluma.systemd
      systemd_default_target: multi-user.target
    - role: buluma.httpd
    - role: ansible-role-varnish
