- become: true
  gather_facts: false
  hosts: all
  name: Prepare
  roles:
  - role: buluma.bootstrap
  tasks:
  - ansible.builtin.apt: update_cache=true cache_valid_time=600
    name: Update apt cache.
    when: ansible_os_family == 'Debian'
  - ansible.builtin.yum:
      name:
      - logrotate
      - systemd-sysv
      state: present
    name: Ensure build dependencies are installed.
    when: ansible_os_family == 'RedHat'
  - ansible.builtin.package: name=curl state=present
    name: Ensure curl is installed.
