---
- name: Prepare
  hosts: all
  gather_facts: no
  become: yes

  roles:
    - role: buluma.bootstrap
    - role: buluma.systemd
      systemd_default_target: multi-user.target
    - role: buluma.httpd

  tasks:
    - name: update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

    - name: ensure build dependencies are installed (RedHat 7+).
      ansible.builtin.yum:
        name:
          - logrotate
          - systemd-sysv
        state: present
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version >= '7'

    - name: ensure build dependencies are installed (RedHat < 7).
      ansible.builtin.yum:
        name: logrotate
        state: present
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version < '7'

    - name: ensure curl is installed.
      package: name=curl state=present
