---
- become: true
  gather_facts: false
- name: Prepare
  hosts: all
  name: Prepare
  pre_tasks:
    - name: Install python3 and sudo
      ansible.builtin.raw: |
        if command -v dnf 2>/dev/null; then
          dnf install -y python3 sudo
        elif command -v apt-get 2>/dev/null; then
          apt-get update -qq && apt-get install -y python3 sudo
        elif command -v apk 2>/dev/null; then
          apk update && apk add python3 sudo
        fi
      become: false
      changed_when: true

    - name: Find EXTERNALLY-MANAGED files
      ansible.builtin.find:
        paths: /usr/lib
        patterns: "EXTERNALLY-MANAGED"
        recurse: true
      register: externally_managed_files

    - name: Remove EXTERNALLY-MANAGED files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ externally_managed_files.files }}"

  roles:
    - role: buluma.bootstrap
  tasks:
    - ansible.builtin.apt: update_cache=true cache_valid_time=600
      name: Update apt cache.
      when: ansible_facts['os_family'] == 'Debian'
    - ansible.builtin.yum:
        name:
          - logrotate
          - systemd-sysv
        state: present
      name: Ensure build dependencies are installed.
      when: ansible_facts['os_family'] == 'RedHat'
    - ansible.builtin.package: name=curl state=present
      name: Ensure curl is installed.
