---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: check the installed varnish version.
      command: varnishd -V
      register: varnish_version_output
      # failed_when: "varnish_version not in varnish_version_output.stderr"
      changed_when: false
      tags: ['skip_ansible_lint']

    - name: verify varnish is running on port 80.
      shell: 'curl -sI localhost:80 | grep -q "Via: .* varnish"'
      changed_when: false
      tags: ['skip_ansible_lint']
      ignore_errors: true  # TODO: final a cleaner way
