- become: true
  gather_facts: false
  hosts: all
  name: Verify
  tasks:
  - changed_when: false
    command: varnishd -V
    name: check the installed varnish version.
    register: varnish_version_output
    tags:
    - skip_ansible_lint
  - changed_when: false
    name: Verify Varnish is running on port 80.
    shell: 'curl -sI localhost:80 | grep -q "Via: .* varnish"'
    tags:
    - skip_ansible_lint
