defaults:
  run:
    working-directory: buluma.varnish
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Check out the codebase.
      uses: actions/checkout@v6
      with:
        path: buluma.varnish
    - name: Set up Python 3.
      uses: actions/setup-python@v6.2.0
      with:
        python-version: 3.x
    - name: Install test dependencies.
      run: pip3 install yamllint
    - name: Lint code.
      run: 'yamllint .

        '
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    steps:
    - name: Check out the codebase.
      uses: actions/checkout@v6
      with:
        path: buluma.varnish
    - name: Set up Python 3.
      uses: actions/setup-python@v6.2.0
      with:
        python-version: 3.x
    - name: Install test dependencies.
      run: pip3 install ansible molecule[docker] docker
    - env:
        ANSIBLE_FORCE_COLOR: '1'
        MOLECULE_DISTRO: ${{ matrix.distro }}
        MOLECULE_PLAYBOOK: ${{ matrix.playbook }}
        PY_COLORS: '1'
      name: Run Molecule tests.
      run: molecule test
    strategy:
      matrix:
        include:
        - distro: rockylinux8
          playbook: converge.yml
        - distro: centos7
          playbook: converge.yml
        - distro: ubuntu1804
          playbook: converge.yml
        - distro: debian10
          playbook: converge.yml
        - distro: centos7
          playbook: version-41.yml
name: CI
'on':
  pull_request: null
  push:
    branches:
    - master
  schedule:
  - cron: 30 3 * * 2
